# Descriptive Statistics: Measures of Central Tendency

## Mean
A number equal to the sum of the data values, divided by the number of data values that were summed.

Commonly referred to as the average.

### Formula
Sum of observations divided by the number of observations

$$
\mu = \frac{\sum_{i=1}^{n} x_i}{n}
$$

### Examples

In [1]:
import pandas as pd
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
df = pd.DataFrame(data)
df.mean()

0    5.5
dtype: float64

In [2]:
nums_list = [2,1,3,4,7]
nums = pd.DataFrame(nums_list)
nums.mean()

0    3.4
dtype: float64

### Exercises (mean)

**Exercise 1 (mean)**

> A consumer group tested the gas mileage of two car models in five trials. Which model averages more miles per gallon?

In [5]:
gallons = pd.DataFrame({
    "Trial" : [1, 2, 3, 4, 5],
    "Model A": [22, 24, 19, 25, 20],
    "Model B": [21, 25, 25, 23, 21]
})
gallons

   Trial  Model A  Model B
0      1       22       21
1      2       24       25
2      3       19       25
3      4       25       23
4      5       20       21

In [6]:
gallons["Model A"].mean()

np.float64(22.0)

In [7]:
gallons["Model B"].mean()

np.float64(23.0)

**Exercise 2 (mean)**
> The table below reports the number of minutes eight randomly selected airline flights were either early (negative values) or late (positive values) arriving at their destinations. Calculate the sample mean.

In [9]:
flights = pd.DataFrame({
    "Flight": [1, 2, 3, 4, 5, 6, 7, 8],
    "Minutes": [12, -10, 32, -4, 0, 16, 5, 18]
})
flights["Minutes"].mean()

np.float64(8.625)

**Exercise 3 (mean)**

>The following table lists the daily percent increase (or decrease) of a stock price over a five-day period. Calculate the mean daily change in the stock price.

In [11]:
stock = pd.DataFrame({
    "Day": [1, 2, 3, 4, 5],
    "Percent Change": [0.018, -0.026, -0.057, -0.039, 0.016]
})
stock["Percent Change"].mean()

np.float64(-0.0176)

**Exercise 4 (mean)**
> The table below lists the points scored by three basketball players over six games. Identify the player with the highest average points per game.

In [12]:
players = pd.DataFrame({
    "Game": [1, 2, 3, 4, 5, 6],
    "Kevin": [17, 16, 8, 21, 25, 18],
    "Paul": [20, 18, 7, 36, 34, 15],
    "Ray": [18, 9, 17, 19, 17, 12]
})

np.float64(15.333333333333334)

In [13]:
players["Kevin"].mean()

np.float64(17.5)

In [14]:
players["Paul"].mean()

np.float64(21.666666666666668)

In [15]:
players["Ray"].mean()

np.float64(15.333333333333334)

**Exercise 5 (mean)**
> A tire store develops a demand forecast that is based on the average demand from the previous three days. In the table below, the demand for tired over a seven-day period is listed. Calculate a demand forecast for January 11.

In [18]:
tires = pd.DataFrame({
    "Day": ["January 4", "January 5", "January 6", "January 7", "January 8", "January 9", "January 10"],
    "Demand": [18, 23, 14, 15, 25, 34, 29]
})
# calculate the mean of the last three days
tires["Demand"].tail(3).mean()

np.float64(29.333333333333332)

Assume that the store calculates a demand forecast every day based on the average demand from the previous three days. Based on the given data, on which days was the demand forecast the most and the least accurate?

In [21]:
tires

          Day  Demand
0   January 4      18
1   January 5      23
2   January 6      14
3   January 7      15
4   January 8      25
5   January 9      34
6  January 10      29

In [22]:
tires["Demand"].rolling(3).mean()

0          NaN
1          NaN
2    18.333333
3    17.333333
4    18.000000
5    24.666667
6    29.333333
Name: Demand, dtype: float64

**Exercise 6 (mean)**
> The average exam score for 10 students in a statistics class was 85. One student dropped the class, changing the average exam score of the remaining students to 90. What was the exam score of the student who dropped the class?

In [30]:
# Calculate the sum of the scores of the 10 students
10 * 85

850

In [32]:
# Calculate the sum of the scores of the 9 students
9 * 90

810

In [33]:
850 - 810

40

**Exercise 7 (mean)**
> The table below lists the ages of the players on a basketball team.

In [24]:
ages = pd.DataFrame({
    "Age": [30, 27, 36, 24, 26, 24, 28, 25, 29, 31]
})

In [25]:
ages["Age"].mean()

np.float64(28.0)

After the oldest player was released and replaced by a new player, the average age of the team was lowered by one year. Determine the age of the new player.

In [34]:
# Calculate the sum of the ages of the 10 players
ages["Age"].sum()

np.int64(280)

In [35]:
# Sum of the ages after the oldest player was released
270
# Difference in the sum of the ages
280 - 270

10

In [41]:
ages.sort_values("Age", ascending=False).head(1)

   Age
2   36

In [42]:
36-10

26