# Descriptive Statistics: Measures of Central Tendency

## Mode

The value (or values) in a set of data values that appears most frequently.

> Some sets of data values have no mode because all the unique values appear the same number of times. Other sets of data values can have more than one mode, such as the get-ready times that several earlier worked-out problems used.

As with the median, extreme values do not affect the mode. However, unlike with the median, the mode can vary much more from sample to sample than can the median or the mean.

*(Synonyms: modal value, modal average)*

### Examples

#### Example 1 (mode)

Mode

In [1]:
import pandas as pd
import numpy as np
import statistics

In [2]:
mode_data = [1, 1, 2, 3, 7,8]

In [3]:
df = pd.DataFrame(mode_data)
df.mode()

   0
0  1

In [4]:
statistics.mode(mode_data)

1

#### Example 2 (mode)

Bi-modal

In [5]:
bimode_data = [1, 1, 2, 3, 7, 8, 8]

In [6]:
df = pd.DataFrame(bimode_data)
df.mode()

   0
0  1
1  8

In [7]:
statistics.mode(bimode_data)

1

<div class="alert alert-block alert-warning">The statistics module in Python will return the first mode it finds. If there are multiple modes, it will return the first one it encounters.</div>

#### Example 3 (mode)

No mode

In [8]:
trimode_data = [1, 1, 2, 3, 7, 8, 8, 7]

In [9]:
df = pd.DataFrame(trimode_data)

In [10]:
df.mode()

   0
0  1
1  7
2  8

<div class="alert alert-block alert-danger">Despite Pandas calculating the mode, a "tri-mode" (or more) is not accepted in statistics.</div>

In [11]:
statistics.mode(trimode_data)

1

<div class="alert alert-block alert-danger">The statistics module will eturn the first mode in the dataset, even though a "multi-mode" is not accepted in statistics.</div>

In [12]:
no_mode = [1, 2, 3, 4, 5, 6]

In [13]:
df = pd.DataFrame(no_mode)

In [14]:
df.mode()

   0
0  1
1  2
2  3
3  4
4  5
5  6

<div class="alert alert-block alert-info">When there is no mode, Pandas will return all values in the dataset.</div>

In [15]:
statistics.mode(no_mode)

1

<div class="alert alert-block alert-danger">When there is no mode, the statistics module will return the first value in the dataset.</div>

### Exercises (mode)

##### Exercise 1 (mode)

The data below lists daily demand for hammers at a hardware store over the last 20 days. Identify the mode.

In [16]:
hammers = [2, 1, 0, 2, 1, 3, 0, 2, 4, 0, 3, 2, 3, 4, 2, 2, 2, 4, 3, 0]

In [17]:
df = pd.DataFrame(hammers)

In [18]:
df.mode()

   0
0  2

In [22]:
statistics.mode(hammers)

2

##### Exercise 2 (mode)

 A grocery store records the time, in minutes, required to check out nine randomly selected customers. Identify the mode of this data set.

In [19]:
minutes = [3, 4, 2, 5, 4, 1, 5, 5, 4]

In [20]:
df = pd.DataFrame(minutes)

In [21]:
df.mode()

   0
0  4
1  5

In [23]:
statistics.mode(minutes)

4

<div class="alert alert-block alert-warning">Remember: the statistics module will return only the first mode in the data frame</div>