## Cross Validation with scikit-learn

1. Cross-validation with `cross_val_score`
2. Cross-validation with `cross_validate`
3. Comparison with train/test split
4. Comparison with train/validation/test split

### Cross Validation with cross_val_score

In [171]:
import pandas as pd
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

In [172]:
df = pd.read_csv('../project/data/another_advertising.csv')

In [173]:
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [174]:
X = df.drop('sales', axis=1)
y = df['sales']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [175]:
model = Ridge(alpha=100)

In [176]:
from sklearn.model_selection import cross_val_score

In [177]:
scores = cross_val_score(model, X_train, y_train, scoring='neg_mean_squared_error', cv=5)

In [178]:
scores

array([ -9.32552967,  -4.9449624 , -11.39665242,  -7.0242106 ,
        -8.38562723])

In [179]:
abs(scores.mean())

np.float64(8.215396464543607)

In [180]:
model = Ridge(alpha=1)

In [181]:
scores = cross_val_score(model, X_train, y_train, scoring='neg_mean_squared_error', cv=5)

In [182]:
abs(scores.mean())

np.float64(3.344839296530695)

In [183]:
model.fit(X_train, y_train)

Ridge(alpha=1)

In [184]:
y_pred = model.predict(X_test)

In [185]:
mean_squared_error(y_test, y_pred)

2.319021579428752

### Cross Validation with cross_validate

The `cross_validate` function differs from `cross_val_score` in two ways:

1. It allows specifying multiple metrics for evaluation.
2. It returns a dictionary containing fit-times, score-times in addition to test score.

In [186]:
X = df.drop('sales', axis=1)
y = df['sales']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [187]:
model = Ridge(alpha=100)

In [188]:
from sklearn.model_selection import cross_validate

In [189]:
scores = cross_validate(model,X_train,y_train,
                         scoring=['neg_mean_absolute_error','neg_mean_squared_error','max_error'],cv=5)

In [190]:
scores

{'fit_time': array([0.00272131, 0.00220966, 0.00285125, 0.00178885, 0.0013268 ]),
 'score_time': array([0.00269842, 0.00257659, 0.00197339, 0.00229669, 0.00143123]),
 'test_neg_mean_absolute_error': array([-2.31243044, -1.74653361, -2.56211701, -2.01873159, -2.27951906]),
 'test_neg_mean_squared_error': array([ -9.32552967,  -4.9449624 , -11.39665242,  -7.0242106 ,
         -8.38562723]),
 'test_max_error': array([ -6.44988486,  -5.58926073, -10.33914027,  -6.61950405,
         -7.75578515])}

In [191]:
pd.DataFrame(scores)

,fit_time,score_time,test_neg_mean_absolute_error,test_neg_mean_squared_error,test_max_error
0,0.002721,0.002698,-2.312430,-9.325530,-6.449885
1,0.002210,0.002577,-1.746534,-4.944962,-5.589261
2,0.002851,0.001973,-2.562117,-11.396652,-10.339140
3,0.001789,0.002297,-2.018732,-7.024211,-6.619504
4,0.001327,0.001431,-2.279519,-8.385627,-7.755785

In [192]:
pd.DataFrame(scores).mean()

fit_time                        0.002180
score_time                      0.002195
test_neg_mean_absolute_error   -2.183866
test_neg_mean_squared_error    -8.215396
test_max_error                 -7.350715
dtype: float64

In [193]:
model = Ridge(alpha=1)

In [194]:
scores = cross_validate(model,X_train,y_train,
                         scoring=['neg_mean_absolute_error','neg_mean_squared_error','max_error'],cv=5)

In [195]:
pd.DataFrame(scores).mean()

fit_time                        0.001874
score_time                      0.002031
test_neg_mean_absolute_error   -1.319685
test_neg_mean_squared_error    -3.344839
test_max_error                 -5.161145
dtype: float64

What sklearn does is a simpler version the next two processes.

### Train/Test Split

In [196]:
X = df.drop('sales', axis=1)
y = df['sales']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [197]:
from sklearn.linear_model import Ridge

In [198]:
model = Ridge(alpha=100)

In [199]:
model.fit(X_train, y_train)

Ridge(alpha=100)

In [200]:
y_pred = model.predict(X_test)

In [201]:
from sklearn.metrics import mean_squared_error

In [202]:
mean_squared_error(y_test, y_pred)

7.34177578903413

In [203]:
model = Ridge(alpha=1)

In [204]:
model.fit(X_train, y_train)

Ridge(alpha=1)

In [205]:
y_pred = model.predict(X_test)

In [206]:
mean_squared_error(y_test, y_pred)

2.319021579428752

### Train/Validation Test Split

In [207]:
X = df.drop('sales', axis=1)
y = df['sales']

In [208]:
X_train, X_holdout, y_train, y_holdout = train_test_split(X, y, test_size=0.3, random_state=101)
X_eval, X_test, y_eval, y_test = train_test_split(X_holdout, y_holdout, test_size=0.5, random_state=101)

In [209]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_eval = scaler.transform(X_eval)
X_test = scaler.transform(X_test)

In [210]:
model = Ridge(alpha=1)

In [166]:
model.fit(X_train, y_train)

Ridge(alpha=1)

In [167]:
y_eval_pred = model.predict(X_eval)

In [168]:
mean_squared_error(y_eval, y_eval_pred)

2.383783075056986

In [169]:
y_final_test_pred = model.predict(X_test)

In [170]:
mean_squared_error(y_test, y_final_test_pred)

2.2542600838005176

## Grid Search

A grid search is a way of training and validating a model on every possible combination of multiple hyperparameters (provided as a dictionary) to find the best combination.

Sci-kit learn provides a way to do this with the `GridSearchCV` class.

In [211]:
X = df.drop('sales',axis=1)
y = df['sales']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [212]:
from sklearn.linear_model import ElasticNet

In [213]:
base_elastic_model = ElasticNet()

In [214]:
param_grid = {'alpha':[0.1,1,5,10,50,100],
              'l1_ratio':[.1, .5, .7, .9, .95, .99, 1]}

In [215]:
from sklearn.model_selection import GridSearchCV

In [223]:
grid_model = GridSearchCV(estimator=base_elastic_model,
                          param_grid=param_grid,
                          scoring='neg_mean_squared_error',
                          cv=5,
                          verbose=1)

In [224]:
grid_model.fit(X_train,y_train)

Fitting 5 folds for each of 42 candidates, totalling 210 fits

GridSearchCV(cv=5, estimator=ElasticNet(),
             param_grid={'alpha': [0.1, 1, 5, 10, 50, 100],
                         'l1_ratio': [0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1]},
             scoring='neg_mean_squared_error', verbose=1)

In [225]:
grid_model.best_estimator_

ElasticNet(alpha=0.1, l1_ratio=1)

In [226]:
grid_model.best_params_

{'alpha': 0.1, 'l1_ratio': 1}

In [227]:
pd.DataFrame(grid_model.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_l1_ratio,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002297,0.000442,0.001172,0.000216,0.1,0.10,"{'alpha': 0.1, 'l1_ratio': 0.1}",-3.453021,-1.405190,-5.789125,-2.187302,-4.645576,-3.496043,1.591601,7
1,0.001979,0.000760,0.000865,0.000213,0.1,0.50,"{'alpha': 0.1, 'l1_ratio': 0.5}",-3.325440,-1.427522,-5.595610,-2.163089,-4.451679,-3.392668,1.506827,6
2,0.001427,0.000131,0.000968,0.000292,0.1,0.70,"{'alpha': 0.1, 'l1_ratio': 0.7}",-3.269880,-1.442432,-5.502437,-2.163950,-4.356738,-3.347088,1.462765,5
3,0.001340,0.000114,0.000981,0.000288,0.1,0.90,"{'alpha': 0.1, 'l1_ratio': 0.9}",-3.221397,-1.465339,-5.416447,-2.173493,-4.263887,-3.308112,1.417693,4
4,0.001580,0.000207,0.001012,0.000264,0.1,0.95,"{'alpha': 0.1, 'l1_ratio': 0.95}",-3.213052,-1.472417,-5.396258,-2.177452,-4.241080,-3.300052,1.406248,3
5,0.001489,0.000202,0.001002,0.000295,0.1,0.99,"{'alpha': 0.1, 'l1_ratio': 0.99}",-3.208124,-1.478489,-5.380242,-2.181097,-4.222968,-3.294184,1.396953,2
6,0.001529,0.000206,0.001038,0.000338,0.1,1.00,"{'alpha': 0.1, 'l1_ratio': 1}",-3.206943,-1.480065,-5.376257,-2.182076,-4.218460,-3.292760,1.394613,1
7,0.001364,0.000081,0.000897,0.000100,1.0,0.10,"{'alpha': 1, 'l1_ratio': 0.1}",-9.827475,-5.261525,-11.875347,-7.449195,-8.542329,-8.591174,2.222939,14
8,0.001549,0.000550,0.000813,0.000337,1.0,0.50,"{'alpha': 1, 'l1_ratio': 0.5}",-8.707071,-4.214228,-10.879261,-6.204545,-7.173031,-7.435627,2.255532,13
9,0.001255,0.000243,0.000906,0.000365,1.0,0.70,"{'alpha': 1, 'l1_ratio': 0.7}",-7.920870,-3.549562,-10.024877,-5.379553,-6.324836,-6.639940,2.206213,12
10,0.000901,0.000018,0.000597,0.000106,1.0,0.90,"{'alpha': 1, 'l1_ratio': 0.9}",-6.983855,-2.790355,-8.997108,-4.414928,-5.545769,-5.746403,2.128364,11
11,0.001018,0.000134,0.000699,0.000186,1.0,0.95,"{'alpha': 1, 'l1_ratio': 0.95}",-6.729435,-2.591285,-8.709842,-4.156317,-5.329916,-5.503359,2.102835,10
12,0.000922,0.000117,0.000663,0.000174,1.0,0.99,"{'alpha': 1, 'l1_ratio': 0.99}",-6.521344,-2.431385,-8.471086,-3.946327,-5.151344,-5.304297,2.079945,9
13,0.000963,0.000085,0.000676,0.000178,1.0,1.00,"{'alpha': 1, 'l1_ratio': 1}",-6.468807,-2.391483,-8.410171,-3.893566,-5.105922,-5.253990,2.073832,8
14,0.001104,0.000230,0.000624,0.000060,5.0,0.10,"{'alpha': 5, 'l1_ratio': 0.1}",-22.979265,-15.547104,-23.668249,-19.921063,-16.262737,-19.675684,3.334901,15
15,0.001081,0.000210,0.000617,0.000085,5.0,0.50,"{'alpha': 5, 'l1_ratio': 0.5}",-27.793488,-18.602269,-27.107849,-23.945227,-18.064635,-23.102694,4.108297,16
16,0.001220,0.000518,0.000685,0.000189,5.0,0.70,"{'alpha': 5, 'l1_ratio': 0.7}",-29.655510,-21.085059,-29.629478,-26.724595,-20.223654,-25.463659,4.077877,18
17,0.000957,0.000166,0.000592,0.000080,5.0,0.90,"{'alpha': 5, 'l1_ratio': 0.9}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19
18,0.001120,0.000368,0.000645,0.000213,5.0,0.95,"{'alpha': 5, 'l1_ratio': 0.95}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19
19,0.001180,0.000296,0.000638,0.000122,5.0,0.99,"{'alpha': 5, 'l1_ratio': 0.99}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19
20,0.000800,0.000003,0.000501,0.000001,5.0,1.00,"{'alpha': 5, 'l1_ratio': 1}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19
21,0.000802,0.000003,0.000504,0.000004,10.0,0.10,"{'alpha': 10, 'l1_ratio': 0.1}",-27.385346,-19.159534,-27.635464,-24.154104,-18.968161,-23.460522,3.794608,17
22,0.000800,0.000005,0.000582,0.000158,10.0,0.50,"{'alpha': 10, 'l1_ratio': 0.5}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19
23,0.000896,0.000133,0.000527,0.000024,10.0,0.70,"{'alpha': 10, 'l1_ratio': 0.7}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19
24,0.000887,0.000172,0.000503,0.000002,10.0,0.90,"{'alpha': 10, 'l1_ratio': 0.9}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19
25,0.000821,0.000038,0.000631,0.000252,10.0,0.95,"{'alpha': 10, 'l1_ratio': 0.95}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19
26,0.001102,0.000177,0.000789,0.000221,10.0,0.99,"{'alpha': 10, 'l1_ratio': 0.99}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19
27,0.001460,0.000420,0.000762,0.000256,10.0,1.00,"{'alpha': 10, 'l1_ratio': 1}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19
28,0.001332,0.000160,0.000847,0.000189,50.0,0.10,"{'alpha': 50, 'l1_ratio': 0.1}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19
29,0.000900,0.000148,0.000510,0.000004,50.0,0.50,"{'alpha': 50, 'l1_ratio': 0.5}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19
30,0.000884,0.000133,0.000541,0.000030,50.0,0.70,"{'alpha': 50, 'l1_ratio': 0.7}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19
31,0.000805,0.000002,0.000586,0.000156,50.0,0.90,"{'alpha': 50, 'l1_ratio': 0.9}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19
32,0.000815,0.000009,0.000509,0.000007,50.0,0.95,"{'alpha': 50, 'l1_ratio': 0.95}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19
33,0.000885,0.000156,0.000509,0.000006,50.0,0.99,"{'alpha': 50, 'l1_ratio': 0.99}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19
34,0.000830,0.000023,0.000553,0.000062,50.0,1.00,"{'alpha': 50, 'l1_ratio': 1}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19
35,0.000807,0.000002,0.000590,0.000166,100.0,0.10,"{'alpha': 100, 'l1_ratio': 0.1}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19
36,0.000808,0.000005,0.000508,0.000005,100.0,0.50,"{'alpha': 100, 'l1_ratio': 0.5}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19
37,0.001125,0.000493,0.000591,0.000073,100.0,0.70,"{'alpha': 100, 'l1_ratio': 0.7}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19
38,0.001118,0.000343,0.000536,0.000026,100.0,0.90,"{'alpha': 100, 'l1_ratio': 0.9}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19
39,0.000817,0.000009,0.000517,0.000022,100.0,0.95,"{'alpha': 100, 'l1_ratio': 0.95}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19
40,0.000838,0.000036,0.000536,0.000043,100.0,0.99,"{'alpha': 100, 'l1_ratio': 0.99}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19
41,0.000930,0.000154,0.000526,0.000034,100.0,1.00,"{'alpha': 100, 'l1_ratio': 1}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,19

In [228]:
y_pred = grid_model.predict(X_test)

In [229]:
mean_squared_error(y_test,y_pred)

2.387342642087474